# Generated by Django 4.2.13 on 2026-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='points_used',
            field=models.IntegerField(default=0),
        ),
    ]
