# Generated by Django 4.2.13 on 2026-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customerorder_points_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
