# Generated by Django 4.2.13 on 2026-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customerorder_gross_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
