# Generated by Django 4.2.13 on 2026-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/'),
        ),
    ]
