# Generated by Django 4.2.13 on 2026-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_first_name_useraccount_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
